{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common-app.serviceAccountName" . }}
  labels: {{- include "common-app.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
{{- if .Values.global.serviceAccount.createToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common-app.serviceAccountName" . }}-token
  labels: {{- include "common-app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "common-app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/service-account-token
{{- end }}
{{- end }}
