apiVersion: v2
name: common-app
description: A general purposes helm chart to deploy various types of applications to Kubernetes
home: https://github.com/ardikabs/helm-charts
type: application
version: 0.3.1
appVersion: "stable"

maintainers:
  - name: ardikabs
    email: me@ardikabs.com
    url: https://site.ardikabs.com
