#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

lookup_latest_tag() {
  git fetch --tags >/dev/null 2>&1

  if ! git describe --tags --abbrev=0 HEAD~ 2>/dev/null; then
    git rev-list --max-parents=0 --first-parent HEAD
  fi
}

filter_charts() {
  while read -r chart; do
    [[ ! -d "$chart" ]] && continue
    local file="$chart/Chart.yaml"
    echo >&2 "Searching $file ..."
    if [[ -f "$file" ]]; then
      echo "$chart"
    else
      echo "WARNING: $file is missing, assuming that '$chart' is not a Helm chart. Skipping." 1>&2
    fi
  done
}

lookup_changed_charts() {
  local commit="$1"
  local chart_dir="$2"

  local changed_files
  changed_files=$(git diff --find-renames --name-only "$commit" -- "$chart_dir")

  local depth=$(($(tr "/" "\n" <<<"$chart_dir" | sed '/^\(\.\)*$/d' | wc -l) + 1))
  local fields="1-${depth}"

  cut -d '/' -f "$fields" <<<"$changed_files" | uniq | filter_charts
}

main() {
  local latest_tag
  latest_tag=$(lookup_latest_tag)

  local changed_charts=()

  while read chart; do
    changed_charts+=($chart)
  done <<<"$(lookup_changed_charts "$latest_tag" "charts")"

  for chart in "${changed_charts[@]}"; do
    echo $chart
  done
}

main "$@"
