{{- if and (.Values.app.service.enabled) (.Values.app.ingress.enabled) -}}
{{- $backendPort := "http" -}}
{{- if hasKey .Values.app.service.ports $backendPort }}
{{- $name := include "common-app.name" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-{{ .Values.global.channel }}
  labels: {{- include "common-app.labels" . | nindent 4 }}
    {{- with .Values.app.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.app.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.app.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.app.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.app.ingress.path | default "/" | quote }}
            pathType: {{ .Values.app.ingress.pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ $name }}-{{ .Values.global.channel }}
                port:
                  name: {{ $backendPort }}
  {{- if .Values.app.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.app.ingress.host | quote }}
    secretName: {{ .Values.app.ingress.tls.secretName }}
  {{- end }}
{{- end }}
{{- end }}
