{{- if and (.Values.job.enabled) (not .Values.job.cron.enabled) (ne .Values.global.channel "canary") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common-app.name" . }}
  labels: {{- include "common-app.labels" . | nindent 4 }}
    {{- with .Values.job.Labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.job.jobAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec: {{ include "common-app.jobSpec" . | nindent 2 }}
{{- end }}