{{- if and (.Values.app.enabled) (.Values.app.service.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common-app.name" . }}
  labels: {{- include "common-app.labels" . | nindent 4 }}
    {{- with .Values.app.service.labels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
  {{- with .Values.app.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.app.service.type }}
  {{- with .Values.app.service.ports }}
  ports:
  {{- range $key, $value := . }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort | default $key }}
      protocol: {{ $value.protocol }}
  {{- end }}
  {{- end }}
  selector: {{- include "common-app.podSelectorLabels" . | nindent 4 }}
---
{{- if eq .Values.global.channel "stable" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | trunc 63 | trimSuffix "-" }}
  labels: {{- include "common-app.labels" . | nindent 4 }}
  {{- with .Values.app.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.app.service.type }}
  {{- with .Values.app.service.ports }}
  ports:
  {{- range $key, $value := . }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort | default $key }}
      protocol: {{ $value.protocol }}
  {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "common-app.releaseName" . }}
{{- end }}
{{- end }}
